FROM python:3.12-alpine

WORKDIR /app
COPY . .
COPY ../requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "app.py"]



